import { StyleSheet } from "react-native";

import { colors } from "./colors";

export const addStyles = StyleSheet.create({
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  spotifyActionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  spotifyDangerBlock: {
    gap: 8,
    paddingTop: 4,
  },
  spotifyDangerRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 8,
  },
  spotifyDangerButton: {
    flex: 1,
    minWidth: 0,
  },
  collapseButton: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  collapseButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.black,
    textTransform: "lowercase",
  },
  dateInsightCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    gap: 4,
  },
  dateInsightTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  dateInsightBody: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    textTransform: "lowercase",
  },
  importStatusCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  importStatusTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  importStatusBody: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
    textTransform: "lowercase",
  },
  previewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  previewTile: {
    width: "31%",
    minHeight: 132,
    justifyContent: "space-between",
    padding: 10,
    gap: 6,
  },
  previewTileActive: {
    borderColor: colors.black,
    borderWidth: 2,
    transform: [{ translateY: -2 }],
  },
  previewType: {
    fontSize: 10,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.4,
  },
  previewMeta: {
    fontSize: 11,
    lineHeight: 14,
    color: colors.text,
    textTransform: "lowercase",
  },
  previewRemoveChip: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFE0E8",
  },
  previewRemoveChipText: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  compactEditorCard: {
    paddingTop: 14,
    paddingBottom: 14,
    gap: 10,
  },
  editorTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.5,
  },
  compactInput: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
  },
  instructionCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    gap: 10,
  },
  brandButton: {
    width: "48%",
    alignItems: "stretch",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
    gap: 2,
    position: "relative",
  },
  brandButtonMain: {
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    minHeight: 74,
  },
  brandHelpButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.line,
  },
  brandHelpButtonText: {
    fontSize: 15,
    fontWeight: "900",
    textTransform: "lowercase",
  },
  brandHint: {
    fontSize: 11,
    color: colors.subtext,
    marginTop: 4,
    textTransform: "lowercase",
  },
});
