import { StyleSheet } from "react-native";

import { colors } from "./colors";

export const appTabStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.white,
  },
  libraryShell: {
    flex: 1,
    backgroundColor: colors.white,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 140,
    gap: 20,
  },
  containerCompact: {
    paddingTop: 10,
    paddingBottom: 116,
    gap: 14,
  },
  libraryHeader: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  appHeader: {
    gap: 14,
  },
  appHeaderCompact: {
    gap: 10,
  },
  brand: {
    fontSize: 34,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -1.1,
  },
  subtitle: {
    fontSize: 18,
    color: colors.text,
    textTransform: "lowercase",
  },
  headerIdentityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  headerIdentityRowCompact: {
    gap: 12,
  },
  headerIdentityText: {
    flex: 1,
    gap: 4,
  },
  headerAvatarBubble: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  headerAvatarImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
  },
  headerAvatarEmoji: {
    fontSize: 30,
  },
  headerAvatarBubbleCompact: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  headerAvatarImageCompact: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  headerAvatarEmojiCompact: {
    fontSize: 24,
  },
  brandCompact: {
    fontSize: 28,
    letterSpacing: -0.9,
  },
  subtitleCompact: {
    fontSize: 16,
  },
  syncText: {
    fontSize: 13,
    color: colors.subtext,
    textTransform: "lowercase",
    lineHeight: 18,
  },
  syncTextCompact: {
    fontSize: 12,
    lineHeight: 16,
  },
  bottomBarWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 18,
    backgroundColor: "transparent",
  },
  toast: {
    alignSelf: "center",
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: colors.black,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  toastText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.white,
    textTransform: "lowercase",
  },
  busyOverlay: {
    position: "absolute",
    inset: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 30,
  },
  busyOverlayCard: {
    minWidth: 220,
    maxWidth: 320,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  busyOverlayTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    textAlign: "center",
  },
  busyOverlayText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
    textAlign: "center",
  },
  screenshotSheetWrap: {
    position: "absolute",
    inset: 0,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 24,
    zIndex: 35,
  },
  screenshotSheet: {
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  screenshotSheetTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  screenshotSheetHeading: {
    flex: 1,
    gap: 4,
  },
  screenshotSheetTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.6,
  },
  screenshotActionButtonSingle: {
    width: "100%",
  },
  screenshotSheetMeta: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  screenshotSheetStatus: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  bottomBar: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  bottomItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  bottomItemLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.subtext,
    textTransform: "lowercase",
    textAlign: "center",
    width: "100%",
    lineHeight: 13,
  },
  bottomIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F6F6F6",
  },
  bottomPlusWrap: {
    width: 78,
    alignItems: "center",
    marginTop: -30,
  },
  bottomPlus: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 6,
    borderColor: colors.white,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  bottomPlusText: {
    fontSize: 36,
    fontWeight: "400",
    color: colors.white,
    marginTop: -2,
  },
  editModalSheet: {
    width: "100%",
    maxHeight: "86%",
    minHeight: 360,
    backgroundColor: colors.white,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 18,
    gap: 14,
  },
  editSheetMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  editSheetContent: {
    gap: 10,
    paddingBottom: 6,
  },
});
