import { StyleSheet } from "react-native";

const colors = {
  white: "#FFFFFF",
  text: "#171717",
  subtext: "#666666",
  line: "#ECECEC",
  pink: "#FF79D5",
  yellow: "#FFC804",
  blue: "#38C0FF",
  green: "#49DE4E",
  purple: "#B889FF",
  black: "#111111",
};

export const appStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.white,
  },
  libraryShell: {
    flex: 1,
    backgroundColor: colors.white,
  },
  scroll: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 140,
    gap: 20,
  },
  containerCompact: {
    paddingTop: 10,
    paddingBottom: 116,
    gap: 14,
  },
  libraryHeader: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  appHeader: {
    gap: 14,
  },
  appHeaderCompact: {
    gap: 10,
  },
  brand: {
    fontSize: 34,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -1.1,
  },
  subtitle: {
    fontSize: 18,
    color: colors.text,
    textTransform: "lowercase",
  },
  headerIdentityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  headerIdentityRowCompact: {
    gap: 12,
  },
  headerIdentityText: {
    flex: 1,
    gap: 4,
  },
  headerAvatarBubble: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  headerAvatarImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
  },
  headerAvatarEmoji: {
    fontSize: 30,
  },
  headerAvatarBubbleCompact: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  headerAvatarImageCompact: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  headerAvatarEmojiCompact: {
    fontSize: 24,
  },
  brandCompact: {
    fontSize: 28,
    letterSpacing: -0.9,
  },
  subtitleCompact: {
    fontSize: 16,
  },
  syncText: {
    fontSize: 13,
    color: colors.subtext,
    textTransform: "lowercase",
    lineHeight: 18,
  },
  syncTextCompact: {
    fontSize: 12,
    lineHeight: 16,
  },
  screen: {
    gap: 14,
  },
  libraryScreen: {
    flex: 1,
  },
  libraryListContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 140,
  },
  libraryListTop: {
    gap: 16,
    marginBottom: 16,
  },
  libraryTopCompactCard: {
    gap: 10,
    paddingTop: 16,
    paddingBottom: 16,
  },
  libraryIntroCompact: {
    fontSize: 14,
    lineHeight: 20,
  },
  compactFilterSection: {
    gap: 8,
  },
  compactFilterHeader: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  compactAccordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  compactAccordionMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  compactAccordionValue: {
    fontSize: 12,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  compactAccordionChevron: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.subtext,
  },
  compactFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  compactPillButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 0,
  },
  libraryListSpacer: {
    height: 12,
  },
  libraryColumn: {
    gap: 12,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 32,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  cardAccentPink: {
    backgroundColor: "#FFDDF4",
  },
  cardAccentBlue: {
    backgroundColor: "#DDF5FF",
  },
  cardAccentYellow: {
    backgroundColor: "#FFF3B6",
  },
  cardAccentGreen: {
    backgroundColor: "#B8FFB6",
  },
  compactCard: {
    gap: 10,
    paddingTop: 16,
    paddingBottom: 16,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  spotifyActionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  spotifyDangerBlock: {
    gap: 8,
    paddingTop: 4,
  },
  spotifyDangerRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 8,
  },
  spotifyDangerButton: {
    flex: 1,
    minWidth: 0,
  },
  statusChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
  },
  statusChipText: {
    fontSize: 12,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  collapseButton: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  collapseButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.black,
    textTransform: "lowercase",
  },
  compactNameCard: {
    backgroundColor: "#FAFAFA",
  },
  dateInsightCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    gap: 4,
  },
  dateInsightTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  dateInsightBody: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    textTransform: "lowercase",
  },
  importStatusCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  importStatusTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  importStatusBody: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.text,
    textTransform: "lowercase",
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.8,
  },
  helper: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.text,
    textTransform: "lowercase",
  },
  label: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  compactNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  compactNameTextWrap: {
    flex: 1,
    gap: 4,
  },
  profileHero: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  profileAvatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarImage: {
    width: 76,
    height: 76,
    borderRadius: 38,
  },
  profileAvatarText: {
    fontSize: 26,
    fontWeight: "900",
    color: colors.white,
  },
  telegramQrCard: {
    marginTop: 10,
    gap: 10,
    alignItems: "center",
    paddingVertical: 8,
  },
  telegramQrImage: {
    width: 176,
    height: 176,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  profileHeroText: {
    flex: 1,
    gap: 4,
  },
  profileStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  profileStatTile: {
    width: "47%",
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 12,
    paddingVertical: 14,
    gap: 4,
  },
  profileStatValue: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  profileStatLabel: {
    fontSize: 13,
    color: colors.subtext,
    fontWeight: "800",
    textTransform: "lowercase",
  },
  stack: {
    gap: 12,
    marginTop: 4,
  },
  input: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.black,
  },
  pillButton: {
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  primaryButton: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  secondaryButton: {
    backgroundColor: colors.white,
    borderColor: colors.line,
  },
  dangerButton: {
    backgroundColor: "#FFF3F7",
    borderColor: "#FFD4E6",
  },
  disabledButton: {
    opacity: 0.45,
  },
  activeTabButton: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  primaryText: {
    color: colors.white,
    fontWeight: "900",
    textTransform: "lowercase",
    fontSize: 16,
  },
  secondaryText: {
    color: colors.black,
    fontWeight: "900",
    textTransform: "lowercase",
    fontSize: 16,
  },
  tabText: {
    color: colors.black,
    fontWeight: "800",
    textTransform: "lowercase",
  },
  activeTabText: {
    color: colors.white,
    fontWeight: "900",
    textTransform: "lowercase",
  },
  tile: {
    backgroundColor: colors.white,
    borderRadius: 28,
    padding: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  tileLarge: {
    minHeight: 164,
  },
  dayDetailTile: {
    minHeight: 146,
    borderRadius: 22,
    padding: 10,
    gap: 5,
  },
  tilePink: {
    backgroundColor: colors.pink,
  },
  tileBlue: {
    backgroundColor: colors.blue,
  },
  tileYellow: {
    backgroundColor: colors.yellow,
  },
  tileGreen: {
    backgroundColor: colors.green,
  },
  itemTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.7,
  },
  itemMeta: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    textTransform: "lowercase",
  },
  metaText: {
    fontSize: 13,
    color: colors.subtext,
    lineHeight: 19,
    textTransform: "lowercase",
  },
  metaDate: {
    fontSize: 11,
    color: "#7D7D7D",
    textTransform: "lowercase",
    maxWidth: 106,
    textAlign: "right",
  },
  dayDetailTitle: {
    fontSize: 13,
    letterSpacing: -0.25,
    lineHeight: 15,
  },
  dayDetailMeta: {
    fontSize: 12,
    lineHeight: 14,
  },
  dayDetailDate: {
    fontSize: 10,
    maxWidth: 56,
  },
  dayDetailOrigin: {
    fontSize: 10,
    lineHeight: 12,
  },
  bottomBarWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 18,
    backgroundColor: "transparent",
  },
  toast: {
    alignSelf: "center",
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: colors.black,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  toastText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.white,
    textTransform: "lowercase",
  },
  busyOverlay: {
    position: "absolute",
    inset: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 30,
  },
  busyOverlayCard: {
    minWidth: 220,
    maxWidth: 320,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  busyOverlayTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    textAlign: "center",
  },
  busyOverlayText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
    textAlign: "center",
  },
  screenshotSheetWrap: {
    position: "absolute",
    inset: 0,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 24,
    zIndex: 35,
  },
  screenshotSheet: {
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  screenshotSheetTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  screenshotSheetHeading: {
    flex: 1,
    gap: 4,
  },
  screenshotSheetTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.6,
  },
  screenshotSheetText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  screenshotActionButton: {
    flex: 1,
  },
  screenshotActionButtonSingle: {
    width: "100%",
  },
  screenshotSheetMeta: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  screenshotSheetStatus: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  bottomBar: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  bottomItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  bottomItemLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.subtext,
    textTransform: "lowercase",
    textAlign: "center",
    width: "100%",
    lineHeight: 13,
  },
  bottomItemLabelActive: {
    color: colors.black,
  },
  bottomIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F6F6F6",
  },
  bottomIconActive: {
    backgroundColor: "#F1F1F1",
  },
  bottomPlusWrap: {
    width: 78,
    alignItems: "center",
    marginTop: -30,
  },
  bottomPlus: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 6,
    borderColor: colors.white,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  bottomPlusText: {
    fontSize: 36,
    fontWeight: "400",
    color: colors.white,
    marginTop: -2,
  },
  tileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  previewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  previewTile: {
    width: "31%",
    minHeight: 132,
    justifyContent: "space-between",
    padding: 10,
    gap: 6,
  },
  previewTileActive: {
    borderColor: colors.black,
    borderWidth: 2,
    transform: [{ translateY: -2 }],
  },
  previewType: {
    fontSize: 10,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.4,
  },
  previewMeta: {
    fontSize: 11,
    lineHeight: 14,
    color: colors.text,
    textTransform: "lowercase",
  },
  previewRemoveChip: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFE0E8",
  },
  previewRemoveChipText: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  compactEditorCard: {
    paddingTop: 14,
    paddingBottom: 14,
    gap: 10,
  },
  editorTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.5,
  },
  compactInput: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
  },
  libraryTile: {
    flex: 1,
    minHeight: 146,
    justifyContent: "space-between",
    paddingTop: 13,
    paddingBottom: 13,
  },
  homeFeatureTile: {
    width: "48%",
    minHeight: 204,
    justifyContent: "space-between",
    paddingTop: 12,
    paddingBottom: 14,
    gap: 8,
  },
  homeTileTextBlock: {
    gap: 8,
  },
  homeTileEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "lowercase",
    letterSpacing: -0.2,
  },
  homeTileTitle: {
    fontSize: 20,
    lineHeight: 23,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.7,
  },
  homeTileBody: {
    fontSize: 13,
    lineHeight: 19,
    textTransform: "lowercase",
    maxWidth: "94%",
  },
  timelineCard: {
    gap: 14,
  },
  dragCaptureLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  timelineMonth: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.5,
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingTop: 2,
    paddingBottom: 2,
  },
  timelineDot: {
    width: 14,
    height: 14,
    borderRadius: 999,
    marginTop: 6,
    borderWidth: 1,
    borderColor: colors.white,
  },
  timelineContent: {
    flex: 1,
    gap: 4,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  timelineHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  timelineType: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  timelineTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.6,
  },
  calendarCard: {
    gap: 14,
  },
  monthLevelCard: {
    gap: 10,
    paddingTop: 16,
    paddingBottom: 16,
  },
  monthLevelTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  monthLevelTextBlock: {
    flex: 1,
    gap: 6,
  },
  monthLevelTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.6,
  },
  monthLevelBody: {
    fontSize: 14,
    lineHeight: 20,
  },
  monthLevelModalText: {
    marginTop: 4,
    fontSize: 15,
    lineHeight: 22,
  },
  calendarTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  calendarTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  calendarTitle: {
    flex: 1,
    fontSize: 26,
    fontWeight: "900",
    color: colors.black,
    textAlign: "center",
    letterSpacing: -0.7,
  },
  calendarArrow: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarTodayButton: {
    width: "auto",
    minWidth: 84,
    paddingHorizontal: 14,
  },
  calendarTodayText: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  calendarArrowText: {
    fontSize: 28,
    color: colors.black,
    marginTop: -2,
  },
  calendarWeekdays: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 4,
  },
  calendarWeekday: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
  },
  calendarDay: {
    width: "13.3%",
    minHeight: 78,
    borderRadius: 18,
    backgroundColor: "#FAFAFA",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 8,
    gap: 5,
  },
  calendarDayMuted: {
    opacity: 0.34,
  },
  calendarDayActive: {
    borderColor: colors.black,
    backgroundColor: "#FFF7D0",
  },
  calendarDayHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  calendarDayNumber: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.black,
  },
  calendarDayNumberMuted: {
    color: "#9A9A9A",
  },
  calendarDayCount: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.subtext,
  },
  calendarDotRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  calendarDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  calendarMore: {
    fontSize: 10,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  calendarStepsText: {
    fontSize: 9,
    color: colors.subtext,
    textTransform: "lowercase",
    marginTop: 1,
  },
  weekStrip: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    paddingVertical: 0,
    paddingRight: 8,
  },
  weekStripScroll: {
    flexGrow: 0,
    maxHeight: 50,
    minHeight: 50,
    marginTop: 2,
    marginBottom: 4,
  },
  dayTypeFilterRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 6,
  },
  dayTypeFilterPill: {
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  calendarMoveBanner: {
    gap: 10,
    paddingTop: 14,
    paddingBottom: 14,
  },
  calendarMoveTitle: {
    marginBottom: 0,
  },
  dayActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  dayActionPill: {
    minHeight: 36,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  dayStepsCard: {
    gap: 4,
    paddingTop: 12,
    paddingBottom: 12,
    borderRadius: 20,
  },
  dayStepsTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  dayStepsValue: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.6,
  },
  dayGridPressable: {
    flex: 1,
    position: "relative",
  },
  daySelectionBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: colors.black,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: colors.white,
  },
  daySelectionBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    color: colors.white,
    textTransform: "lowercase",
  },
  weekDayChip: {
    minWidth: 48,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    gap: 1,
  },
  weekDayChipActive: {
    backgroundColor: colors.black,
    borderColor: colors.black,
    transform: [{ scale: 1.02 }],
  },
  weekDayName: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  weekDayNameActive: {
    color: colors.white,
  },
  weekDayNumber: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.black,
  },
  weekDayNumberActive: {
    color: colors.white,
  },
  dayModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,17,17,0.18)",
    justifyContent: "flex-end",
    paddingHorizontal: 18,
    paddingBottom: 16,
    paddingTop: 88,
  },
  dayModalSheet: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
    paddingTop: 14,
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
    overflow: "hidden",
  },
  guideModalSheet: {
    width: "100%",
    maxHeight: "72%",
    minHeight: 320,
    backgroundColor: colors.white,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 18,
    gap: 14,
  },
  editModalSheet: {
    width: "100%",
    maxHeight: "86%",
    minHeight: 360,
    backgroundColor: colors.white,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 18,
    gap: 14,
  },
  editSheetMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  editSheetContent: {
    gap: 10,
    paddingBottom: 6,
  },
  dayModalTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  dayModalHeading: {
    flex: 1,
    gap: 2,
  },
  dayModalClose: {
    minWidth: 84,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
  },
  dayModalCloseText: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  resultModalClose: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  resultModalCloseText: {
    fontSize: 24,
    lineHeight: 24,
    fontWeight: "500",
    color: colors.black,
    marginTop: -2,
  },
  dayModalScroll: {
    flex: 1,
    minHeight: 1,
    marginTop: 2,
  },
  dayModalContent: {
    gap: 8,
    paddingBottom: 14,
  },
  dayModalGridRow: {
    gap: 8,
    marginBottom: 8,
  },
  dayModalTitle: {
    fontSize: 24,
    lineHeight: 29,
    letterSpacing: -0.8,
  },
  tileTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  typeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  instructionCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    gap: 10,
  },
  brandButton: {
    width: "48%",
    alignItems: "stretch",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
    gap: 2,
    position: "relative",
  },
  brandButtonMain: {
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    minHeight: 74,
  },
  brandHelpButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.line,
  },
  brandHelpButtonText: {
    fontSize: 15,
    fontWeight: "900",
    textTransform: "lowercase",
  },
  brandLogo: {
    fontSize: 20,
    fontWeight: "900",
    color: colors.black,
    textTransform: "uppercase",
  },
  brandHint: {
    fontSize: 11,
    color: colors.subtext,
    marginTop: 4,
    textTransform: "lowercase",
  },
  sectionHero: {
    borderRadius: 32,
    padding: 18,
    gap: 10,
    backgroundColor: "#FFDDF4",
    borderWidth: 1,
    borderColor: colors.pink,
  },
  sectionHeroAlt: {
    backgroundColor: "#DDF5FF",
    borderColor: colors.blue,
  },
});
