import { StyleSheet } from "react-native";

const colors = {
  white: "#FFFFFF",
  text: "#171717",
  subtext: "#666666",
  line: "#ECECEC",
  pink: "#FF79D5",
  yellow: "#FFC804",
  blue: "#38C0FF",
  green: "#49DE4E",
  purple: "#B889FF",
  black: "#111111",
};

export const appStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.white,
  },
  scroll: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 140,
    gap: 18,
  },
  brand: {
    fontSize: 34,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -1.1,
  },
  subtitle: {
    fontSize: 18,
    color: colors.text,
    textTransform: "lowercase",
  },
  syncText: {
    fontSize: 13,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  screen: {
    gap: 16,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 32,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  cardAccentPink: {
    backgroundColor: "#FFDDF4",
  },
  cardAccentBlue: {
    backgroundColor: "#DDF5FF",
  },
  cardAccentYellow: {
    backgroundColor: "#FFF3B6",
  },
  cardAccentGreen: {
    backgroundColor: "#D9FFD9",
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.8,
  },
  helper: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.text,
    textTransform: "lowercase",
  },
  label: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  stack: {
    gap: 12,
    marginTop: 4,
  },
  input: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 17,
    color: colors.black,
  },
  pillButton: {
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  primaryButton: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  secondaryButton: {
    backgroundColor: colors.white,
    borderColor: colors.line,
  },
  dangerButton: {
    backgroundColor: "#FFF3F7",
    borderColor: "#FFD4E6",
  },
  disabledButton: {
    opacity: 0.45,
  },
  activeTabButton: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  primaryText: {
    color: colors.white,
    fontWeight: "900",
    textTransform: "lowercase",
    fontSize: 16,
  },
  secondaryText: {
    color: colors.black,
    fontWeight: "900",
    textTransform: "lowercase",
    fontSize: 16,
  },
  tabText: {
    color: colors.black,
    fontWeight: "800",
    textTransform: "lowercase",
  },
  activeTabText: {
    color: colors.white,
    fontWeight: "900",
    textTransform: "lowercase",
  },
  tile: {
    backgroundColor: colors.white,
    borderRadius: 28,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  tileLarge: {
    minHeight: 164,
  },
  tilePink: {
    backgroundColor: colors.pink,
  },
  tileBlue: {
    backgroundColor: colors.blue,
  },
  tileYellow: {
    backgroundColor: colors.yellow,
  },
  tileGreen: {
    backgroundColor: colors.green,
  },
  itemTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.7,
  },
  itemMeta: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    textTransform: "lowercase",
  },
  metaText: {
    fontSize: 13,
    color: colors.subtext,
    lineHeight: 19,
    textTransform: "lowercase",
  },
  metaDate: {
    fontSize: 11,
    color: "#7D7D7D",
    textTransform: "lowercase",
    maxWidth: 106,
    textAlign: "right",
  },
  bottomBarWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 18,
    backgroundColor: "transparent",
  },
  bottomBar: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  bottomItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  bottomItemLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  bottomItemLabelActive: {
    color: colors.black,
  },
  bottomIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F6F6F6",
  },
  bottomIconActive: {
    backgroundColor: "#F1F1F1",
  },
  bottomPlusWrap: {
    width: 78,
    alignItems: "center",
    marginTop: -30,
  },
  bottomPlus: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 6,
    borderColor: colors.white,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  bottomPlusText: {
    fontSize: 36,
    fontWeight: "400",
    color: colors.white,
    marginTop: -2,
  },
  tileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  libraryTile: {
    width: "48%",
    minHeight: 154,
    justifyContent: "space-between",
    paddingTop: 14,
    paddingBottom: 14,
  },
  tileTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  typeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  instructionCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    gap: 10,
  },
  brandButton: {
    minWidth: 150,
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  brandLogo: {
    fontSize: 20,
    fontWeight: "900",
    color: colors.black,
    textTransform: "uppercase",
  },
  brandLogoSpotify: {
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  brandLogoLivelib: {
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  brandLogoLetterboxd: {
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  brandLogoLastfm: {
    fontSize: 19,
    fontWeight: "900",
    fontStyle: "italic",
    letterSpacing: 0.2,
  },
  brandLogoKinopoisk: {
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  brandLogoMubi: {
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  brandHint: {
    fontSize: 11,
    color: colors.subtext,
    marginTop: 4,
    textTransform: "lowercase",
  },
  sectionHero: {
    borderRadius: 32,
    padding: 20,
    gap: 12,
    backgroundColor: "#FFDDF4",
    borderWidth: 1,
    borderColor: colors.pink,
  },
  sectionHeroAlt: {
    backgroundColor: "#DDF5FF",
    borderColor: colors.blue,
  },
});
