import { StyleSheet } from "react-native";

import { colors } from "./colors";

export const sharedStyles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  screen: {
    gap: 14,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 32,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  cardAccentPink: {
    backgroundColor: "#FFDDF4",
  },
  cardAccentBlue: {
    backgroundColor: "#DDF5FF",
  },
  cardAccentYellow: {
    backgroundColor: "#FFF3B6",
  },
  cardAccentGreen: {
    backgroundColor: "#B8FFB6",
  },
  compactCard: {
    gap: 10,
    paddingTop: 16,
    paddingBottom: 16,
  },
  statusChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
  },
  statusChipText: {
    fontSize: 12,
    color: colors.subtext,
    textTransform: "lowercase",
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.8,
  },
  helper: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.text,
    textTransform: "lowercase",
  },
  label: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: "900",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  stack: {
    gap: 12,
    marginTop: 4,
  },
  input: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.black,
  },
  pillButton: {
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  primaryButton: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  disabledButton: {
    opacity: 0.45,
  },
  primaryText: {
    color: colors.white,
    fontWeight: "900",
    textTransform: "lowercase",
    fontSize: 16,
  },
  secondaryText: {
    color: colors.black,
    fontWeight: "900",
    textTransform: "lowercase",
    fontSize: 16,
  },
  tile: {
    backgroundColor: colors.white,
    borderRadius: 28,
    padding: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  tilePink: {
    backgroundColor: colors.pink,
  },
  tileBlue: {
    backgroundColor: colors.blue,
  },
  tileYellow: {
    backgroundColor: colors.yellow,
  },
  tileGreen: {
    backgroundColor: colors.green,
  },
  itemTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
    letterSpacing: -0.7,
  },
  metaText: {
    fontSize: 13,
    color: colors.subtext,
    lineHeight: 19,
    textTransform: "lowercase",
  },
  metaDate: {
    fontSize: 11,
    color: "#7D7D7D",
    textTransform: "lowercase",
    maxWidth: 106,
    textAlign: "right",
  },
  calendarTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  calendarTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  calendarTitle: {
    flex: 1,
    fontSize: 26,
    fontWeight: "900",
    color: colors.black,
    textAlign: "center",
    letterSpacing: -0.7,
  },
  calendarArrow: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarTodayButton: {
    width: "auto",
    minWidth: 84,
    paddingHorizontal: 14,
  },
  calendarTodayText: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  calendarArrowText: {
    fontSize: 28,
    color: colors.black,
    marginTop: -2,
  },
  calendarWeekdays: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 4,
  },
  calendarWeekday: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
    color: colors.subtext,
    textTransform: "lowercase",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
  },
  calendarDay: {
    width: "13.3%",
    minHeight: 78,
    borderRadius: 18,
    backgroundColor: "#FAFAFA",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 8,
    gap: 5,
  },
  calendarDayMuted: {
    opacity: 0.34,
  },
  calendarDayHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  calendarDayNumber: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.black,
  },
  calendarDayCount: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.subtext,
  },
  dayModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,17,17,0.18)",
    justifyContent: "flex-end",
    paddingHorizontal: 18,
    paddingBottom: 16,
    paddingTop: 88,
  },
  dayModalSheet: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
    paddingTop: 14,
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
    overflow: "hidden",
  },
  guideModalSheet: {
    width: "100%",
    maxHeight: "72%",
    minHeight: 320,
    backgroundColor: colors.white,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 18,
    gap: 14,
  },
  dayModalTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  dayModalHeading: {
    flex: 1,
    gap: 2,
  },
  dayModalClose: {
    minWidth: 84,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
  },
  dayModalCloseText: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.black,
    textTransform: "lowercase",
  },
  dayModalScroll: {
    flex: 1,
    minHeight: 1,
    marginTop: 2,
  },
  dayModalContent: {
    gap: 8,
    paddingBottom: 14,
  },
  dayModalTitle: {
    fontSize: 24,
    lineHeight: 29,
    letterSpacing: -0.8,
  },
  sectionHero: {
    borderRadius: 32,
    padding: 18,
    gap: 10,
    backgroundColor: "#FFDDF4",
    borderWidth: 1,
    borderColor: colors.pink,
  },
  sectionHeroAlt: {
    backgroundColor: "#DDF5FF",
    borderColor: colors.blue,
  },
});
