import { type ThemeMode } from "../shared/everyyou/domain";

export const mobileThemes = {
  light: {
    mode: "light" as const,
    background: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceMuted: "#FAFAFA",
    elevatedSurface: "#F6F6F6",
    border: "#ECECEC",
    text: "#171717",
    mutedText: "#666666",
    quietText: "#7D7D7D",
    buttonSecondaryBg: "#FFFFFF",
    buttonSecondaryBorder: "#ECECEC",
    buttonSecondaryText: "#171717",
    buttonPrimaryBg: "#111111",
    buttonPrimaryBorder: "#111111",
    buttonPrimaryText: "#FFFFFF",
    buttonDangerBg: "#FFF3F7",
    buttonDangerBorder: "#FFD4E6",
    buttonDangerText: "#171717",
    inputBg: "#FFFFFF",
    inputBorder: "#ECECEC",
    inputText: "#171717",
    inputPlaceholder: "#8A8A8A",
    toastBg: "#111111",
    toastText: "#FFFFFF",
    bottomBarBg: "#FFFFFF",
    bottomBarBorder: "#ECECEC",
    bottomIconBg: "#F6F6F6",
    bottomIconActiveBg: "#F1F1F1",
    bottomIconText: "#171717",
    bottomLabel: "#666666",
    bottomLabelActive: "#171717",
    bottomPlusBorder: "#FFFFFF",
    overlay: "rgba(17,17,17,0.18)",
    accentPink: "#FFDDF4",
    accentBlue: "#DDF5FF",
    accentYellow: "#FFF3B6",
    accentGreen: "#B8FFB6",
  },
  dark: {
    mode: "dark" as const,
    background: "#0F1115",
    surface: "#171A20",
    surfaceMuted: "#1B1F26",
    elevatedSurface: "#20242C",
    border: "#2A313B",
    text: "#F5F7FA",
    mutedText: "#AEB6C2",
    quietText: "#8F98A6",
    buttonSecondaryBg: "#1A1E25",
    buttonSecondaryBorder: "#313845",
    buttonSecondaryText: "#F5F7FA",
    buttonPrimaryBg: "#F5F7FA",
    buttonPrimaryBorder: "#F5F7FA",
    buttonPrimaryText: "#111111",
    buttonDangerBg: "#331D28",
    buttonDangerBorder: "#5A2F42",
    buttonDangerText: "#FFF5F8",
    inputBg: "#14181E",
    inputBorder: "#2F3743",
    inputText: "#F5F7FA",
    inputPlaceholder: "#8F98A6",
    toastBg: "#F5F7FA",
    toastText: "#111111",
    bottomBarBg: "#171A20",
    bottomBarBorder: "#2A313B",
    bottomIconBg: "#20242C",
    bottomIconActiveBg: "#2B313C",
    bottomIconText: "#F5F7FA",
    bottomLabel: "#AEB6C2",
    bottomLabelActive: "#F5F7FA",
    bottomPlusBorder: "#171A20",
    overlay: "rgba(0,0,0,0.54)",
    accentPink: "#FF79D5",
    accentBlue: "#38C0FF",
    accentYellow: "#FFC804",
    accentGreen: "#49DE4E",
  },
};

export function getTheme(mode: ThemeMode) {
  return mobileThemes[mode];
}
