create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  owner_key text not null,
  owner_kind text not null check (owner_kind in ('telegram', 'app')),
  event_name text not null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists app_events_owner_key_idx on public.app_events (owner_key, created_at desc);
create index if not exists app_events_event_name_idx on public.app_events (event_name, created_at desc);

create table if not exists public.analysis_usage_v2 (
  id bigint generated by default as identity primary key,
  owner_key text not null,
  owner_kind text not null check (owner_kind in ('telegram', 'app')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists analysis_usage_v2_owner_key_idx on public.analysis_usage_v2 (owner_key, created_at desc);
