create table if not exists public.connected_sources (
  id bigint generated by default as identity primary key,
  owner_key text not null,
  owner_kind text not null check (owner_kind in ('telegram', 'app')),
  platform text not null check (platform in ('lastfm', 'letterboxd')),
  profile text not null,
  last_synced_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (owner_key, platform)
);

create index if not exists connected_sources_owner_key_idx
  on public.connected_sources (owner_key, updated_at desc);

create index if not exists connected_sources_platform_idx
  on public.connected_sources (platform, updated_at desc);
